version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: housing_postgres
    environment:
      POSTGRES_DB: housing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ml_network

  mlflow:
    build:
      context: ./mlflow
      dockerfile: Dockerfile
    container_name: housing_mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow
    depends_on:
      - postgres
    networks:
      - ml_network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: housing_streamlit
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=housing_db
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - postgres
      - mlflow
    volumes:
      - ./models:/app/models
    networks:
      - ml_network

volumes:
  postgres_data:
  mlflow_data:

networks:
  ml_network:
    driver: bridge